import { SKETCHER_EVENTS, validateSketcherEventPayload } from '../core/sketcher-draft/index.js';
import { validateSettingsApplyFailed,validateSettingsApplyRequested,validateSettingsChanged,validateSettingsProposalChanged,validateSettingsResetRequested,SETTINGS_EVENTS } from '../core/settings-authority/index.js';
import { validateApplicationViewChanged,validateApplicationViewChangeFailed,validateApplicationViewChangeRequested,validateWorkspaceConsumerContextChanged } from '../core/workspace-consumers/event-contracts.js';
export const APPLICATION_EVENTS=Object.freeze({CHANGE_REQUESTED:'applicationView:changeRequested',CHANGED:'applicationView:changed',CHANGE_FAILED:'applicationView:changeFailed',CONTEXT_CHANGED:'workspaceConsumerContext:changed'});
export { SETTINGS_EVENTS, SKETCHER_EVENTS };
export const EVENT_TOPICS=Object.freeze({DATASET_LOAD_REQUESTED:'dataset:loadRequested',DATASET_CLEAR_REQUESTED:'dataset:clearRequested',DATASET_LOADED:'dataset:loaded',DATASET_LOAD_FAILED:'dataset:loadFailed',DATASET_CLEARED:'dataset:cleared',WORKSPACE_SNAPSHOT_CHANGED:'workspace:snapshotChanged',VIEWPORT_SELECTION_REQUESTED:'viewport:selectionRequested',VIEWPORT_ENTITY_SELECTED:'viewport:entitySelected',ANALYSIS_CAPABILITIES_CHANGED:'analysis:capabilitiesChanged',ANALYSIS_SESSION_OPEN_REQUESTED:'analysis:sessionOpenRequested',ANALYSIS_SESSION_OVERRIDE_REQUESTED:'analysis:sessionOverrideRequested',ANALYSIS_SESSION_RESET_REQUESTED:'analysis:sessionResetRequested',ANALYSIS_SESSION_CLOSE_REQUESTED:'analysis:sessionCloseRequested',ANALYSIS_SESSION_CHANGED:'analysis:sessionChanged',ANALYSIS_REQUESTED:'analysis:requested',ANALYSIS_STARTED:'analysis:started',ANALYSIS_COMPLETED:'analysis:completed',ANALYSIS_FAILED:'analysis:failed',ANALYSIS_LEDGER_CHANGED:'analysis:ledgerChanged',ANALYSIS_LEDGER_ACTIVE_REQUESTED:'analysis:ledgerActiveRequested',ANALYSIS_LEDGER_COMPARISON_REQUESTED:'analysis:ledgerComparisonRequested',ANALYSIS_LEDGER_COMPARISON_RESET_REQUESTED:'analysis:ledgerComparisonResetRequested',ANALYSIS_LEDGER_CLEAR_REQUESTED:'analysis:ledgerClearRequested',ANALYSIS_LEDGER_FAILED:'analysis:ledgerFailed',ANALYSIS_EXPORT_REQUESTED:'analysis:exportRequested',ANALYSIS_EXPORT_COMPLETED:'analysis:exportCompleted',ANALYSIS_EXPORT_FAILED:'analysis:exportFailed',...APPLICATION_EVENTS,...SETTINGS_EVENTS,...SKETCHER_EVENTS});
const SKETCHER_EVENT_SET=new Set(Object.values(SKETCHER_EVENTS));
export function assertEventPayload(topic,payload){if(SKETCHER_EVENT_SET.has(topic))return validateSketcherEventPayload(topic,payload);PAYLOAD_VALIDATORS.get(topic)?.(payload)}
const PAYLOAD_VALIDATORS=new Map([
[EVENT_TOPICS.DATASET_LOAD_REQUESTED,validateDatasetLoadRequested],[EVENT_TOPICS.DATASET_CLEAR_REQUESTED,validateOptionalEmptyPayload],[EVENT_TOPICS.DATASET_LOADED,validateDatasetLoaded],[EVENT_TOPICS.DATASET_LOAD_FAILED,validateDatasetLoadFailed],[EVENT_TOPICS.DATASET_CLEARED,validateDatasetCleared],[EVENT_TOPICS.WORKSPACE_SNAPSHOT_CHANGED,validateSnapshotChanged],[EVENT_TOPICS.VIEWPORT_SELECTION_REQUESTED,validateSelectionRequested],[EVENT_TOPICS.VIEWPORT_ENTITY_SELECTED,validateEntitySelected],[EVENT_TOPICS.ANALYSIS_CAPABILITIES_CHANGED,validateCapabilitiesChanged],[EVENT_TOPICS.ANALYSIS_SESSION_OPEN_REQUESTED,validateSessionOpenRequested],[EVENT_TOPICS.ANALYSIS_SESSION_OVERRIDE_REQUESTED,validateSessionOverrideRequested],[EVENT_TOPICS.ANALYSIS_SESSION_RESET_REQUESTED,validateSessionIdentity],[EVENT_TOPICS.ANALYSIS_SESSION_CLOSE_REQUESTED,validateOptionalEmptyPayload],[EVENT_TOPICS.ANALYSIS_SESSION_CHANGED,validateSessionChanged],[EVENT_TOPICS.ANALYSIS_REQUESTED,validateAnalysisRequested],[EVENT_TOPICS.ANALYSIS_STARTED,validateAnalysisLifecycle],[EVENT_TOPICS.ANALYSIS_COMPLETED,validateAnalysisCompleted],[EVENT_TOPICS.ANALYSIS_FAILED,validateAnalysisFailed],[EVENT_TOPICS.ANALYSIS_LEDGER_CHANGED,validateLedgerChanged],[EVENT_TOPICS.ANALYSIS_LEDGER_ACTIVE_REQUESTED,validateLedgerEntryRequest],[EVENT_TOPICS.ANALYSIS_LEDGER_COMPARISON_REQUESTED,validateComparisonRequest],[EVENT_TOPICS.ANALYSIS_LEDGER_COMPARISON_RESET_REQUESTED,validateOptionalEmptyPayload],[EVENT_TOPICS.ANALYSIS_LEDGER_CLEAR_REQUESTED,validateOptionalEmptyPayload],[EVENT_TOPICS.ANALYSIS_LEDGER_FAILED,validateFailure],[EVENT_TOPICS.ANALYSIS_EXPORT_REQUESTED,validateExportRequested],[EVENT_TOPICS.ANALYSIS_EXPORT_COMPLETED,validateExportCompleted],[EVENT_TOPICS.ANALYSIS_EXPORT_FAILED,validateFailure],[APPLICATION_EVENTS.CHANGE_REQUESTED,validateApplicationViewChangeRequested],[APPLICATION_EVENTS.CHANGED,validateApplicationViewChanged],[APPLICATION_EVENTS.CHANGE_FAILED,validateApplicationViewChangeFailed],[APPLICATION_EVENTS.CONTEXT_CHANGED,validateWorkspaceConsumerContextChanged],[SETTINGS_EVENTS.PROPOSAL_CHANGED,validateSettingsProposalChanged],[SETTINGS_EVENTS.APPLY_REQUESTED,validateSettingsApplyRequested],[SETTINGS_EVENTS.CHANGED,validateSettingsChanged],[SETTINGS_EVENTS.APPLY_FAILED,validateSettingsApplyFailed],[SETTINGS_EVENTS.RESET_REQUESTED,validateSettingsResetRequested],]);
const SELECTION_SOURCES=new Set(['tree','viewport','api']),EXPORT_FORMATS=new Set(['json','csv','markdown']);
function validateDatasetLoadRequested(p){assertRecord(p,EVENT_TOPICS.DATASET_LOAD_REQUESTED);if(!(isRecord(p.rawPackage)||Array.isArray(p.rawPackage)))throw new TypeError('dataset:loadRequested payload.rawPackage must be an object or array.');if(p.sourceName!==undefined&&typeof p.sourceName!=='string')throw new TypeError('dataset:loadRequested payload.sourceName must be a string.')}
function validateOptionalEmptyPayload(p){if(p!==undefined&&!isRecord(p))throw new TypeError('Event payload must be omitted or an object.')}
function validateDatasetLoaded(p){assertRecord(p,EVENT_TOPICS.DATASET_LOADED);assertNonEmptyString(p.datasetId,'datasetId',EVENT_TOPICS.DATASET_LOADED);assertNonNegativeInteger(p.nodeCount,'nodeCount',EVENT_TOPICS.DATASET_LOADED)}
function validateDatasetLoadFailed(p){assertRecord(p,EVENT_TOPICS.DATASET_LOAD_FAILED);assertNonEmptyString(p.message,'message',EVENT_TOPICS.DATASET_LOAD_FAILED);if(p.sourceName!==undefined&&typeof p.sourceName!=='string')throw new TypeError('dataset:loadFailed payload.sourceName must be a string.')}
function validateDatasetCleared(p){assertRecord(p,EVENT_TOPICS.DATASET_CLEARED);assertNonNegativeInteger(p.version,'version',EVENT_TOPICS.DATASET_CLEARED)}
function validateSnapshotChanged(p){assertRecord(p,EVENT_TOPICS.WORKSPACE_SNAPSHOT_CHANGED);if(!isRecord(p.snapshot))throw new TypeError('workspace:snapshotChanged payload.snapshot must be an object.')}
function validateSelectionRequested(p){assertRecord(p,EVENT_TOPICS.VIEWPORT_SELECTION_REQUESTED);assertNonEmptyString(p.entityId,'entityId',EVENT_TOPICS.VIEWPORT_SELECTION_REQUESTED);validateSelectionSource(p.source,EVENT_TOPICS.VIEWPORT_SELECTION_REQUESTED)}
function validateEntitySelected(p){assertRecord(p,EVENT_TOPICS.VIEWPORT_ENTITY_SELECTED);assertNonEmptyString(p.entityId,'entityId',EVENT_TOPICS.VIEWPORT_ENTITY_SELECTED);if(p.type!==undefined&&!['pipe','support'].includes(p.type))throw new TypeError("viewport:entitySelected payload.type must be 'pipe' or 'support'.");if(p.properties!==undefined&&!isRecord(p.properties))throw new TypeError('viewport:entitySelected payload.properties must be an object.');if(p.source!==undefined)validateSelectionSource(p.source,EVENT_TOPICS.VIEWPORT_ENTITY_SELECTED)}
function validateCapabilitiesChanged(p){assertRecord(p,EVENT_TOPICS.ANALYSIS_CAPABILITIES_CHANGED);if(typeof p.targetId!=='string')throw new TypeError('analysis:capabilitiesChanged targetId must be a string.');if(!Array.isArray(p.capabilities))throw new TypeError('analysis:capabilitiesChanged capabilities must be an array.');p.capabilities.forEach((c)=>{assertRecord(c,EVENT_TOPICS.ANALYSIS_CAPABILITIES_CHANGED);assertNonEmptyString(c.analysisType,'analysisType',EVENT_TOPICS.ANALYSIS_CAPABILITIES_CHANGED);assertNonEmptyString(c.label,'label',EVENT_TOPICS.ANALYSIS_CAPABILITIES_CHANGED);if(typeof c.enabled!=='boolean')throw new TypeError('Analysis capability enabled must be boolean.')})}
function validateSessionOpenRequested(p){assertRecord(p,EVENT_TOPICS.ANALYSIS_SESSION_OPEN_REQUESTED);assertNonEmptyString(p.analysisType,'analysisType',EVENT_TOPICS.ANALYSIS_SESSION_OPEN_REQUESTED);assertNonEmptyString(p.targetId,'targetId',EVENT_TOPICS.ANALYSIS_SESSION_OPEN_REQUESTED)}
function validateSessionOverrideRequested(p){validateSessionIdentity(p);assertNonEmptyString(p.fieldKey,'fieldKey',EVENT_TOPICS.ANALYSIS_SESSION_OVERRIDE_REQUESTED);if(!['string','number'].includes(typeof p.value)&&p.value!==null)throw new TypeError('analysis:sessionOverrideRequested value must be string, number, or null.')}
function validateSessionIdentity(p){assertRecord(p,'analysis session event');assertNonEmptyString(p.sessionId,'sessionId','analysis session event')}
function validateSessionChanged(p){assertRecord(p,EVENT_TOPICS.ANALYSIS_SESSION_CHANGED);assertNonNegativeInteger(p.version,'version',EVENT_TOPICS.ANALYSIS_SESSION_CHANGED);if(p.session!==null&&!isRecord(p.session))throw new TypeError('analysis:sessionChanged session is invalid.');if(p.session){assertNonEmptyString(p.session.sessionId,'session.sessionId',EVENT_TOPICS.ANALYSIS_SESSION_CHANGED);assertNonEmptyString(p.session.analysisType,'session.analysisType',EVENT_TOPICS.ANALYSIS_SESSION_CHANGED);assertNonEmptyString(p.session.targetId,'session.targetId',EVENT_TOPICS.ANALYSIS_SESSION_CHANGED)}}
function validateAnalysisRequested(p){assertRecord(p,EVENT_TOPICS.ANALYSIS_REQUESTED);assertNonEmptyString(p.analysisType,'analysisType',EVENT_TOPICS.ANALYSIS_REQUESTED);assertNonEmptyString(p.targetId,'targetId',EVENT_TOPICS.ANALYSIS_REQUESTED);validateOptionalSessionId(p,EVENT_TOPICS.ANALYSIS_REQUESTED)}
function validateAnalysisLifecycle(p){assertRecord(p,'analysis lifecycle');assertNonEmptyString(p.requestId,'requestId','analysis lifecycle');assertNonEmptyString(p.analysisType,'analysisType','analysis lifecycle');assertNonEmptyString(p.targetId,'targetId','analysis lifecycle');validateOptionalSessionId(p,'analysis lifecycle')}
function validateAnalysisCompleted(p){validateAnalysisLifecycle(p);if(!isRecord(p.result))throw new TypeError('analysis:completed result must be an object.')}
function validateAnalysisFailed(p){validateAnalysisLifecycle(p);assertNonEmptyString(p.code,'code',EVENT_TOPICS.ANALYSIS_FAILED);assertNonEmptyString(p.message,'message',EVENT_TOPICS.ANALYSIS_FAILED);if(p.details!==undefined&&!isRecord(p.details))throw new TypeError('analysis:failed details must be an object.')}
function validateLedgerChanged(p){assertRecord(p,EVENT_TOPICS.ANALYSIS_LEDGER_CHANGED);if(!isRecord(p.ledger)||p.ledger.schema!=='analysis-ledger/v1')throw new TypeError('analysis:ledgerChanged requires analysis-ledger/v1.');if(!Array.isArray(p.ledger.entries))throw new TypeError('Analysis ledger entries must be an array.')}
function validateLedgerEntryRequest(p){assertRecord(p,'analysis ledger request');assertNonEmptyString(p.entryId,'entryId','analysis ledger request')}
function validateComparisonRequest(p){validateLedgerEntryRequest(p);if(!['left','right'].includes(p.side))throw new TypeError("analysis:ledgerComparisonRequested side must be 'left' or 'right'.")}
function validateFailure(p){assertRecord(p,'analysis failure event');assertNonEmptyString(p.code,'code','analysis failure event');assertNonEmptyString(p.message,'message','analysis failure event')}
function validateExportRequested(p){assertRecord(p,EVENT_TOPICS.ANALYSIS_EXPORT_REQUESTED);if(!EXPORT_FORMATS.has(p.format))throw new TypeError('analysis:exportRequested format is invalid.')}
function validateExportCompleted(p){assertRecord(p,EVENT_TOPICS.ANALYSIS_EXPORT_COMPLETED);if(!isRecord(p.artifact)||p.artifact.schema!=='analysis-export-artifact/v1')throw new TypeError('analysis:exportCompleted artifact is invalid.')}
function validateOptionalSessionId(p,t){if(p.sessionId!==undefined&&p.sessionId!=='')assertNonEmptyString(p.sessionId,'sessionId',t)}
function validateSelectionSource(v,t){if(!SELECTION_SOURCES.has(v))throw new TypeError(`${t} source must be tree, viewport, or api.`)}
function assertRecord(v,t){if(!isRecord(v))throw new TypeError(`${t} payload must be an object.`)}
function assertNonEmptyString(v,f,t){if(typeof v!=='string'||v.trim()==='')throw new TypeError(`${t} payload.${f} must be a non-empty string.`)}
function assertNonNegativeInteger(v,f,t){if(!Number.isInteger(v)||v<0)throw new TypeError(`${t} payload.${f} must be a non-negative integer.`)}
function isRecord(v){return v!==null&&typeof v==='object'&&!Array.isArray(v)}
