export function renderWorkspaceLayout(rootElement) {
  rootElement.replaceChildren();
  const shell = rootElement.ownerDocument.createElement('div');
  shell.innerHTML = workspaceMarkup();
  const style = rootElement.ownerDocument.createElement('style');
  style.textContent = shellStyles();
  rootElement.append(style, shell.firstElementChild);
}

function workspaceMarkup() {
  return `<div class="application-shell" data-role="application-shell">
    <header class="application-navigation-shell">
      <div class="application-navigation-shell__bar">
        <div class="application-brand" aria-label="Simplified Analysis application"><span class="application-brand__mark" aria-hidden="true">SA</span><span class="application-brand__label">Simplified Analysis</span></div>
        <nav class="application-navigation" data-role="application-navigation" aria-label="Application views"></nav>
        <button class="application-overflow__toggle" data-role="application-overflow-toggle" type="button" aria-expanded="false" aria-controls="application-overflow-menu"><span aria-hidden="true">•••</span><span class="visually-hidden">More application views</span></button>
        <output class="application-build-identity" data-role="application-build-identity" aria-label="Application build identity"></output>
      </div>
      <div id="application-overflow-menu" class="application-overflow__menu" data-role="application-overflow-menu" role="menu" aria-label="More application views" hidden></div>
      <output class="application-navigation__status" data-role="application-navigation-status" aria-live="polite"></output>
      <output class="application-global-error" data-role="application-global-error" role="alert" hidden></output>
    </header>
    <div class="application-view application-view--home" data-application-view="HOME"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="home-consumer-root"></div></div>
    <div class="application-view application-view--workspace" data-application-view="WORKSPACE" data-role="workspace-view-root" hidden aria-hidden="true">
      <section class="application-tab-state" data-role="application-tab-status" hidden></section>
      <main class="workspace-shell" aria-label="Analysis Workspace">
        <aside class="workspace-panel tree-panel" data-panel="tree" aria-label="Dataset tree and layers">
          <header class="panel-header"><span class="panel-eyebrow">Analysis Workspace</span><h1>Dataset Tree</h1></header>
          <section class="dataset-toolbar" aria-label="Dataset actions"><div class="dataset-toolbar__actions"><button type="button" data-action="import-dataset">Import JSON</button><button type="button" data-action="clear-dataset" disabled>Clear</button></div><input data-role="dataset-file" type="file" accept=".json,application/json" hidden><output data-role="tree-status">No dataset loaded</output><p class="dataset-error" data-role="tree-error" hidden></p></section>
          <section class="layer-summary" aria-label="Dataset summary"><span data-role="summary-pipes">Pipes 0</span><span data-role="summary-supports">Supports 0</span></section>
          <div class="tree-list" data-role="tree-list"><p class="panel-empty">Import a supported workspace JSON package.</p></div>
        </aside>
        <section class="workspace-panel viewport-panel" data-panel="viewport" aria-label="3D viewport">
          <header class="viewport-toolbar"><div><span class="panel-eyebrow">Read-only model review</span><h2>Model Viewport</h2></div><div class="viewport-toolbar__status"><output data-role="viewport-status">No dataset loaded</output><div class="viewport-toolbar__actions" aria-label="Viewport navigation"><button type="button" data-viewport-action="fit">Fit View</button><button type="button" data-viewport-action="reset">Reset View</button></div></div></header>
          <div class="viewport-stage" data-webgl-host data-role="viewport-render-host" aria-label="Read-only model viewport"></div><footer class="viewport-footer" data-role="viewport-selection">Selection: none</footer>
        </section>
        <aside class="workspace-panel properties-panel" data-panel="properties" aria-label="Properties and analysis actions">
          <header class="panel-header"><span class="panel-eyebrow">Model and contextual workflow</span><h2>Properties &amp; Actions</h2></header>
          <div data-role="shared-model-summary"></div><div data-role="topology-summary"></div><div data-role="support-restraint-summary"></div><div data-role="model-load-summary"></div><div data-role="support-load-screening-summary"></div><div data-role="vertical-beam-summary"></div><div data-role="model-calculation-summary"></div><div data-role="model-support-load-summary"></div>
          <div class="properties-content" data-role="properties-content"><p class="panel-empty">Select an entity to inspect its properties.</p></div>
        </aside>
      </main>
    </div>
    <div class="application-view application-view--load-calc" data-application-view="LOAD_CALC" hidden aria-hidden="true"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="load-calc-consumer-root"></div></div>
    <div class="application-view application-view--pcf" data-application-view="PCF" hidden aria-hidden="true"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="pcf-consumer-root"></div></div>
    <div class="application-view application-view--sketcher" data-application-view="SKETCHER" hidden aria-hidden="true"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="sketcher-consumer-root"></div></div>
    <div class="application-view application-view--three-d-calc" data-application-view="THREE_D_CALC" hidden aria-hidden="true"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="three-d-calc-consumer-root"></div></div>
    <div class="application-view application-view--pipe-solver" data-application-view="PIPE_SOLVER" hidden aria-hidden="true"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="pipe-solver-consumer-root"></div></div>
    <div class="application-view application-view--reports" data-application-view="REPORTS" hidden aria-hidden="true"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="reports-consumer-root"></div></div>
    <div class="application-view application-view--qa" data-application-view="QA" hidden aria-hidden="true"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="qa-consumer-root"></div></div>
    <div class="application-view application-view--settings" data-application-view="SETTINGS" hidden aria-hidden="true"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="settings-consumer-root"></div></div>
    <div class="application-view application-view--debug" data-application-view="DEBUG" hidden aria-hidden="true"><section class="application-tab-state" data-role="application-tab-status" hidden></section><div data-role="debug-consumer-root">${unavailableView('Debug','Debug is not implemented in the current runtime.')}</div></div>
  </div>`;
}

function unavailableView(title, message) { return `<section class="unavailable-view"><h1>${title}</h1><p>${message}</p></section>`; }

function shellStyles() {
  return `
    .application-shell{display:grid;grid-template-rows:auto minmax(0,1fr);height:100vh;min-width:0;overflow:hidden;background:var(--workspace-canvas);color:var(--workspace-text)}
    .application-navigation-shell{position:relative;z-index:20;display:grid;border-bottom:1px solid var(--workspace-border);background:var(--workspace-panel-strong);box-shadow:0 4px 14px rgba(2,6,23,.26)}
    .application-navigation-shell__bar{display:flex;align-items:center;gap:10px;min-width:0;padding:7px 12px 5px}.application-brand{display:flex;align-items:center;gap:8px;flex:0 0 auto;color:#f8fafc;font-weight:800;white-space:nowrap}.application-brand__mark{display:grid;place-items:center;width:28px;height:28px;border-radius:7px;background:#2563eb;color:#fff;font-size:11px;letter-spacing:.04em}.application-brand__label{font-size:13px}
    .application-navigation{display:flex;align-items:center;gap:5px;flex:1 1 auto;min-width:0;overflow:hidden}.application-navigation__button,.application-overflow__item,.application-overflow__toggle{display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid transparent;border-radius:7px;padding:7px 9px;background:transparent;color:#94a3b8;font:inherit;font-size:12px;font-weight:700;white-space:nowrap;cursor:pointer;transition:background .16s ease,border-color .16s ease,color .16s ease}.application-navigation__button:hover,.application-navigation__button:focus-visible,.application-overflow__item:hover,.application-overflow__item:focus-visible,.application-overflow__toggle:hover,.application-overflow__toggle:focus-visible{border-color:#475569;background:#111c30;color:#e2e8f0;outline:2px solid rgba(96,165,250,.45);outline-offset:1px}.application-navigation__button:disabled,.application-overflow__item:disabled{color:#64748b;cursor:not-allowed;opacity:.72}.application-navigation__button--active{border-color:#3b82f6;background:#172554;color:#dbeafe}.application-navigation__button--blocked:not(.application-navigation__button--active){color:#cbd5e1}.application-navigation__icon{width:17px;height:17px;flex:0 0 auto}.application-navigation__indicator{width:7px;height:7px;border-radius:999px;background:#64748b;box-shadow:0 0 0 2px rgba(100,116,139,.15)}[data-content-state="READY"] .application-navigation__indicator{background:#22c55e}[data-content-state="EMPTY"] .application-navigation__indicator,[data-content-state="BLOCKED"] .application-navigation__indicator{background:#f59e0b}[data-content-state="INVALID"] .application-navigation__indicator,[data-content-state="ERROR"] .application-navigation__indicator{background:#ef4444}[data-content-state="UNAVAILABLE"] .application-navigation__indicator{background:#64748b}
    .application-build-identity{flex:0 0 auto;max-width:260px;overflow:hidden;text-overflow:ellipsis;color:#64748b;font:11px ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap}.application-overflow__toggle{display:none;flex:0 0 auto}.application-overflow__menu{position:absolute;right:12px;top:48px;z-index:30;display:grid;min-width:210px;padding:7px;border:1px solid #334155;border-radius:8px;background:#0b1628;box-shadow:0 18px 40px rgba(0,0,0,.45)}.application-overflow__menu[hidden]{display:none}.application-overflow__item{justify-content:flex-start;width:100%}
    .application-navigation__status{min-height:18px;padding:0 12px 5px;color:#93c5fd;font-size:11px}.application-global-error{margin:0 12px 7px;padding:8px 10px;border:1px solid #7f1d1d;border-radius:6px;background:#450a0a;color:#fecaca;font-size:12px}.application-global-error[hidden]{display:none}
    .application-view{min-width:0;min-height:0;overflow:hidden}.application-view[hidden]{display:none!important}.application-view--workspace .workspace-shell{height:100%}.application-view--home,.application-view--reports,.application-view--load-calc,.application-view--pcf,.application-view--sketcher,.application-view--three-d-calc,.application-view--pipe-solver,.application-view--qa,.application-view--settings,.application-view--debug{overflow:auto;background:var(--workspace-canvas)}
    .application-tab-state{display:grid;gap:8px;max-width:1460px;margin:14px auto 0;padding:13px 15px;border:1px solid #334155;border-left-width:4px;border-radius:7px;background:#0b1628}.application-tab-state[hidden]{display:none}.application-tab-state[data-content-state="EMPTY"],.application-tab-state[data-content-state="BLOCKED"]{border-left-color:#f59e0b}.application-tab-state[data-content-state="INVALID"],.application-tab-state[data-content-state="ERROR"]{border-left-color:#ef4444}.application-tab-state[data-content-state="UNAVAILABLE"]{border-left-color:#64748b}.application-tab-state h2{margin:0;font-size:15px}.application-tab-state p{margin:0;color:#cbd5e1}.application-tab-state__action{font-weight:800;color:#fbbf24!important}.application-tab-state__evidence{display:flex;flex-wrap:wrap;gap:8px;margin:0}.application-tab-state__evidence div{min-width:110px;padding:7px 9px;border-radius:5px;background:#060b14}.application-tab-state__evidence dt{color:#94a3b8;font-size:10px;text-transform:uppercase}.application-tab-state__evidence dd{margin:3px 0 0;font-weight:800}.application-tab-state details{color:#cbd5e1}.application-tab-state ul{margin:7px 0 0;padding-left:20px}
    .home-consumer,.reports-consumer,.load-calc-consumer,.pcf-consumer,.sketcher-consumer,.three-d-calc-consumer,.pipe-solver-consumer,.qa-consumer,.settings-consumer{display:grid;gap:14px;max-width:1500px;margin:0 auto;padding:18px;min-width:0}
    .home-consumer__header,.reports-consumer__header,.load-calc-consumer__header,.pcf-consumer__header,.sketcher-consumer__header,.three-d-calc-consumer__header,.pipe-solver-consumer__header,.qa-consumer__header,.settings-consumer__header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.home-consumer__header h1,.reports-consumer__header h1,.load-calc-consumer__header h1,.pcf-consumer__header h1,.sketcher-consumer__header h1,.three-d-calc-consumer__header h1,.pipe-solver-consumer__header h1,.qa-consumer__header h1,.settings-consumer__header h1{margin:4px 0 0}
    .home-consumer__header p,.pcf-consumer__claim,.sketcher-consumer__claim,.reports-consumer__disclaimer,.reports-consumer__footer,.load-calc-consumer__claim,.three-d-calc-consumer__claim,.pipe-solver-consumer__claim,.qa-consumer__claim,.settings-consumer__claim{max-width:680px;color:#fbbf24;font-weight:700}
    .home-card,.reports-card,.load-calc-card,.pcf-card,.sketcher-card,.three-d-calc-card,.pipe-solver-card,.qa-card,.settings-card{min-width:0;padding:14px;border:1px solid var(--workspace-border);border-radius:7px;background:var(--workspace-panel)}.home-card h2,.reports-card h2,.load-calc-card h2,.pcf-card h2,.sketcher-card h2,.three-d-calc-card h2,.pipe-solver-card h2,.qa-card h2,.settings-card h2{margin:0 0 10px;font-size:14px}
    .home-card dl,.reports-card dl,.load-calc-card dl,.pcf-card dl,.sketcher-card dl,.three-d-calc-card dl,.pipe-solver-card dl,.qa-card dl,.settings-card dl{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:0}.home-card dl div,.reports-card dl div,.load-calc-card dl div,.pcf-card dl div,.sketcher-card dl div,.three-d-calc-card dl div,.pipe-solver-card dl div,.qa-card dl div,.settings-card dl div{min-width:0;padding:8px;background:#060b14}.home-card dt,.reports-card dt,.load-calc-card dt,.sketcher-card dt,.three-d-calc-card dt,.pipe-solver-card dt,.qa-card dt,.settings-card dt{color:var(--workspace-muted);font-size:11px}.home-card dd,.reports-card dd,.load-calc-card dd,.sketcher-card dd,.three-d-calc-card dd,.pipe-solver-card dd,.qa-card dd,.settings-card dd{margin:4px 0 0;overflow-wrap:anywhere;font-weight:700}
    .home-consumer__actions,.pcf-consumer__actions,.qa-consumer__actions,.settings-consumer__actions{display:flex;flex-wrap:wrap;gap:8px}.home-consumer__actions button,.pcf-consumer button,.pcf-consumer input,.pcf-consumer textarea,.qa-consumer button,.settings-consumer button,.settings-consumer select{border:1px solid #334155;border-radius:5px;padding:8px;background:#0b1628;color:var(--workspace-text)}
    .pcf-consumer__file,.settings-field{display:grid;gap:6px}.settings-field small{color:var(--workspace-muted)}.settings-field__error{color:#fca5a5}.settings-consumer__controls{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.settings-table-wrap,.pcf-consumer__table-wrap{max-width:100%;overflow:auto}.settings-consumer table,.pcf-consumer table{width:100%;border-collapse:collapse;font-size:12px}.settings-consumer th,.settings-consumer td,.pcf-consumer th,.pcf-consumer td{padding:8px;border-bottom:1px solid var(--workspace-border);text-align:left;vertical-align:top;overflow-wrap:anywhere}.settings-consumer th,.pcf-consumer th{color:#bfdbfe;white-space:nowrap}
    .pcf-consumer textarea{box-sizing:border-box;width:100%;min-height:240px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.pcf-consumer__status{display:block;min-height:22px;color:#bfdbfe}.pcf-consumer pre{max-width:520px;white-space:pre-wrap;overflow-wrap:anywhere}
    .sketcher-consumer__statuses{display:grid;gap:5px;max-width:520px;color:#bfdbfe}.sketcher-toolbar{display:flex;flex-wrap:wrap;align-items:end;gap:7px;padding:12px;border:1px solid var(--workspace-border);border-radius:7px;background:var(--workspace-panel)}.sketcher-toolbar label{display:grid;gap:4px;color:var(--workspace-muted);font-size:11px}.sketcher-toolbar button,.sketcher-toolbar select{border:1px solid #334155;border-radius:5px;padding:8px;background:#0b1628;color:var(--workspace-text)}.sketcher-toolbar button:focus-visible,.sketcher-toolbar select:focus-visible,.sketcher-surface:focus-visible{outline:2px solid rgba(96,165,250,.65);outline-offset:2px}.sketcher-toolbar button[aria-pressed="true"]{border-color:#fbbf24;color:#fde68a}.sketcher-toolbar button:disabled{color:#64748b;cursor:not-allowed}
    .sketcher-workspace{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,360px);gap:14px;min-height:650px}.sketcher-stage{position:relative;min-width:0;overflow:hidden;border:1px solid var(--workspace-border);border-radius:7px;background:#020617}.sketcher-surface{display:block;width:100%;height:620px;touch-action:none;cursor:crosshair}.sketcher-pointer{position:absolute;left:10px;bottom:8px;padding:4px 7px;border-radius:4px;background:rgba(2,6,23,.82);color:#bfdbfe;font-size:11px}.sketcher-sidebar{display:grid;align-content:start;gap:12px}.sketcher-grid-line{stroke:#172033;stroke-width:1}.sketcher-segment{stroke:#60a5fa;stroke-width:5;cursor:pointer}.sketcher-node{fill:#f8fafc;stroke:#1d4ed8;stroke-width:3;cursor:pointer}.sketcher-selected{stroke:#fbbf24!important;fill:#fde68a}.sketcher-node-label,.sketcher-length-label{fill:#e2e8f0;font-size:12px;pointer-events:none}.sketcher-length-label{fill:#93c5fd}.sketcher-diagnostic-list{display:grid;gap:7px;margin:0;padding-left:18px;font-size:12px}.sketcher-diagnostic--error{color:#fca5a5}.sketcher-diagnostic--warning{color:#fde68a}.sketcher-diagnostic--info{color:#bfdbfe}.sketcher-consumer__footer{color:var(--workspace-muted)}
    .home-consumer__loading{padding:20px;color:var(--workspace-muted)}.unavailable-view{max-width:760px;margin:40px auto;padding:20px;border:1px solid var(--workspace-border);border-radius:7px;background:var(--workspace-panel)}
    .reports-consumer__controls,.load-calc-consumer__controls,.three-d-calc-consumer__controls,.pipe-solver-consumer__controls{display:flex;flex-wrap:wrap;align-items:end;gap:8px;padding:12px;border:1px solid var(--workspace-border);border-radius:7px;background:var(--workspace-panel)}.reports-consumer__controls label,.pipe-solver-consumer__controls label{display:grid;gap:5px;min-width:220px;color:var(--workspace-muted);font-size:11px}.reports-consumer__controls select,.reports-consumer__controls button,.load-calc-consumer__controls button,.three-d-calc-consumer__controls button,.pipe-solver-consumer__controls button,.pipe-solver-consumer__controls select{border:1px solid #334155;border-radius:5px;padding:8px;background:#0b1628;color:var(--workspace-text)}
    .load-calc-consumer__controls button[aria-disabled="true"],.three-d-calc-consumer__controls button[aria-disabled="true"],.pipe-solver-consumer__controls button[aria-disabled="true"]{color:#94a3b8;cursor:not-allowed}.reports-consumer__controls output,.load-calc-consumer__controls output,.three-d-calc-consumer__controls output,.pipe-solver-consumer__controls output{flex-basis:100%;color:#bfdbfe}
    .reports-table-wrap,.load-calc-table-wrap,.three-d-calc-table-wrap,.pipe-solver-table-wrap{max-width:100%;overflow:auto}.reports-card table,.load-calc-card table,.three-d-calc-card table,.pipe-solver-card table{width:100%;border-collapse:collapse;font-size:12px}.reports-card th,.reports-card td,.load-calc-card th,.load-calc-card td,.three-d-calc-card th,.three-d-calc-card td,.pipe-solver-card th,.pipe-solver-card td{padding:8px;border-bottom:1px solid var(--workspace-border);text-align:left;vertical-align:top;overflow-wrap:anywhere}.reports-card th,.load-calc-card th,.three-d-calc-card th,.pipe-solver-card th{color:#bfdbfe;white-space:nowrap}.load-calc-card code,.three-d-calc-card code,.pipe-solver-card code,.pipe-solver-card pre{white-space:pre-wrap;overflow-wrap:anywhere}.pipe-solver-card input{min-width:130px;border:1px solid #334155;border-radius:4px;padding:6px;background:#060b14;color:var(--workspace-text)}.pipe-solver-ledger-row--active{background:#1d2433}
    .visually-hidden{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
    @media(max-width:1100px){.sketcher-workspace{grid-template-columns:minmax(0,1fr)}.home-card dl,.reports-card dl,.load-calc-card dl,.pcf-card dl,.sketcher-card dl,.three-d-calc-card dl,.pipe-solver-card dl,.qa-card dl,.settings-card dl{grid-template-columns:repeat(2,minmax(0,1fr))}.application-build-identity{max-width:150px}}
    @media(max-width:1100px){.application-navigation__button[data-navigation-priority="OVERFLOW"]{display:none}.application-overflow__toggle{display:inline-flex}.application-brand__label{display:none}.application-build-identity{max-width:120px}}
    @media(max-width:760px){.application-shell{height:auto;min-height:100vh;overflow:visible}.application-view{overflow:visible}.application-view--workspace .workspace-shell{height:auto}.application-navigation-shell__bar{gap:6px;padding-inline:8px}.application-build-identity{display:none}.home-consumer__header,.reports-consumer__header,.load-calc-consumer__header,.pcf-consumer__header,.sketcher-consumer__header,.three-d-calc-consumer__header,.pipe-solver-consumer__header,.qa-consumer__header,.settings-consumer__header{display:grid}.home-card dl,.reports-card dl,.load-calc-card dl,.pcf-card dl,.sketcher-card dl,.three-d-calc-card dl,.pipe-solver-card dl,.qa-card dl,.settings-card dl{grid-template-columns:minmax(0,1fr)}.application-tab-state{margin:10px 8px 0}}
  `;
}
