import fs from 'node:fs';
import { expect, test } from '@playwright/test';
import { lfeaSelectionIdentity } from '../src/core/lfea-consumer/index.js';
import { convergenceConsumerFixture, q4ConsumerFixture, t3ConsumerFixture } from '../scripts/lfea-007-fixtures.mjs';

const q4 = q4ConsumerFixture({ projection:true, sourceArtifacts:true });
const t3 = t3ConsumerFixture();
const convergence = convergenceConsumerFixture();
const NAVIGATION = ['Home','Workspace','Load Calc','PCF','Sketcher','3D Calc','Pipe Solver','Local FEA','Reports','QA','Settings','Debug'];
const WORKSPACE_FIXTURE = {
  schema:'inputxml-managed-stage/v1', units:{length:'mm'}, objects:[
    {id:'PIPE-LFEA',sourceId:'PIPE-LFEA',name:'Pipe LFEA',type:'PIPE',points:[{x:0,y:0,z:0},{x:1000,y:0,z:0}]},
  ],
};
async function openLocalFea(page) { const navigation=page.getByRole('navigation',{name:'Application views'});const button=navigation.getByRole('button',{name:'Local FEA',exact:true});await expect(button).toHaveAttribute('aria-disabled','false');await button.click();await expect(page.getByRole('heading',{name:'Local FEA',exact:true})).toBeVisible(); }
async function importSource(page,name,value) { const text=typeof value==='string'?value:JSON.stringify(value);await page.locator('[data-role="lfea-source-file"]').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(text)}); }

test('Local FEA is dataset-independent, accessible and renders exact qualified review evidence', async ({page}) => {
  await page.goto('/');const navigation=page.getByRole('navigation',{name:'Application views'});await expect(navigation.getByRole('button')).toHaveText(NAVIGATION);expect((await page.evaluate(()=>AnalysisWorkspace.getSnapshot())).status).toBe('empty');await openLocalFea(page);await expect(page.getByText('No qualified LFEA review loaded.').first()).toBeVisible();expect(await page.locator('[data-webgl-host]').count()).toBe(1);expect(await page.locator('[data-application-view="LOCAL_FEA"] canvas').count()).toBe(0);
  await page.evaluate(()=>{globalThis.__lfeaEvents={analysis:0,loads:0};EventBus.subscribe('analysis:requested',()=>{globalThis.__lfeaEvents.analysis+=1;});EventBus.subscribe('dataset:loadRequested',()=>{globalThis.__lfeaEvents.loads+=1;});});
  await importSource(page,'qualified-review.json',q4.review);await expect(page.locator('.lfea-status')).toContainText('Qualified ENGINEERING_REVIEW');const session=await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerSession());expect(session.status).toBe('QUALIFIED');expect(session.resultMode).toBe('RAW');expect(session.layerVisibility.PROJECTED_STRESS).toBe(false);
  const model=await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel());expect(model.rawStress.authority).toBe('AUTHORITATIVE_RAW_ELEMENT_OR_INTEGRATION_POINT_STRESS');expect(model.geometry.nodes[0].deformedX).toBe(q4.review.geometryReview.nodes[0].deformedX);expect(model.geometry.nodes[0].deformedY).toBe(q4.review.geometryReview.nodes[0].deformedY);expect(model.display.deformationScale).toBe(10);await expect(page.locator('.lfea-svg__stress-point')).toHaveCount(q4.review.rawStressReview.rows.length);await expect(page.locator('.lfea-svg__deformed')).toHaveCount(q4.review.geometryReview.elements.length);await page.getByLabel('DEFORMED REVIEW GEOMETRY').uncheck();await expect(page.locator('.lfea-svg__deformed')).toHaveCount(0);await page.getByLabel('DEFORMED REVIEW GEOMETRY').check();await expect(page.locator('.lfea-svg__deformed')).toHaveCount(q4.review.geometryReview.elements.length);
  const nodeId=q4.review.geometryReview.nodes[0].nodeId;await page.locator('.lfea-svg__node').first().click();await expect(page.locator(`[data-lfea-table-record="${nodeId}"]`)).toHaveClass(/lfea-table__selected/);await page.locator(`[data-lfea-table-record="${nodeId}"]`).focus();await page.keyboard.press('Enter');expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerSession())).selectedRecord.identity).toBe(nodeId);
  const raw=q4.review.rawStressReview.rows[0],rawId=lfeaSelectionIdentity('RAW_STRESS_LOCATION',raw);await page.getByRole('button',{name:'Raw Stress',exact:true}).click();await page.locator(`[data-lfea-table-record="${rawId}"]`).click();expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerSession())).selectedRecord.identity).toBe(rawId);await expect(page.locator('.lfea-record-details')).toContainText(raw.resultLocationId);
  const reaction=q4.review.reactionReview.rows[0],reactionId=lfeaSelectionIdentity('REACTION',reaction);await page.getByRole('button',{name:'Displacements and Reactions',exact:true}).click();await page.locator(`[data-lfea-table-record="${reactionId}"]`).click();expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerSession())).selectedRecord.identity).toBe(reactionId);await expect(page.locator('.lfea-record-details')).toContainText(reaction.component);
  const governingBefore=(await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel())).rawStress.governing.semanticHash;await page.getByLabel('Result mode').selectOption('PROJECTED');await page.getByLabel('Stress component').selectOption('SX');await page.getByLabel('PROJECTED STRESS').check();await expect(page.locator('.lfea-svg__projected-point')).toHaveCount(4);await page.getByRole('button',{name:'Projected Stress',exact:true}).click();await expect(page.getByText('NON-AUTHORITATIVE REVIEW PROJECTION',{exact:true})).toBeVisible();const projected=q4.review.projectedStressReview.nodalValues.find((row)=>row.stressComponent==='SX');const projectedId=lfeaSelectionIdentity('PROJECTED_STRESS_LOCATION',projected);await page.locator(`[data-lfea-table-record="${projectedId}"]`).click();expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerSession())).selectedRecord.identity).toBe(projectedId);await expect(page.locator('.lfea-record-details')).toContainText(projected.projectionPatchId);expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel())).rawStress.governing.semanticHash).toBe(governingBefore);expect(await page.evaluate(()=>globalThis.__lfeaEvents)).toEqual({analysis:0,loads:0});
  await navigation.getByRole('button',{name:'Local FEA',exact:true}).focus();await page.keyboard.press('ArrowRight');await expect(navigation.getByRole('button',{name:'Reports',exact:true})).toBeFocused();
});

test('qualified export downloads exact supplied bytes and failed replacement preserves prior evidence', async ({page}) => {
  await page.addInitScript(()=>{globalThis.__lfeaUrlAudit={created:0,revoked:0};const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=(blob)=>{globalThis.__lfeaUrlAudit.created+=1;return create(blob);};URL.revokeObjectURL=(url)=>{globalThis.__lfeaUrlAudit.revoked+=1;return revoke(url);};});
  await page.goto('/');await openLocalFea(page);await importSource(page,'qualified-export.json',q4.exportValue);await expect(page.locator('.lfea-status')).toContainText('Qualified EVIDENCE_EXPORT');await page.getByRole('button',{name:'Supplied Files',exact:true}).click();const expected=q4.exportValue.files.find((row)=>row.path==='review.json');const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download review.json',exact:true}).click()]);expect(download.suggestedFilename()).toBe('review.json');expect(fs.readFileSync(await download.path(),'utf8')).toBe(expected.content);await expect.poll(()=>page.evaluate(()=>globalThis.__lfeaUrlAudit)).toEqual({created:1,revoked:1});const acceptedHash=(await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel())).semanticHash;
  await importSource(page,'invalid.json','{');await expect(page.locator('.lfea-status')).toContainText('Previous qualified review retained.');expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel())).semanticHash).toBe(acceptedHash);expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaLoadedExport())).semanticHash).toBe(q4.exportValue.semanticHash);
  await page.locator('[data-role="lfea-source-file"]').setInputFiles({name:'invalid-utf8.json',mimeType:'application/json',buffer:Buffer.from([0xff,0xfe])});await expect(page.locator('.lfea-status')).toContainText('valid UTF-8');expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel())).semanticHash).toBe(acceptedHash);
  await page.locator('[data-role="lfea-source-file"]').setInputFiles({name:'oversized.json',mimeType:'application/json',buffer:Buffer.alloc(16777217)});await expect(page.locator('.lfea-status')).toContainText('LFEA_CAPACITY_BLOCKED');expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel())).semanticHash).toBe(acceptedHash);
});

test('convergence level selection resolves the exact unpaged source record', async ({page}) => { await page.goto('/');await openLocalFea(page);await importSource(page,'convergence-review.json',convergence.review);await page.getByRole('button',{name:'Convergence',exact:true}).click();const level=convergence.review.convergenceReview.levels[0];const levelId=lfeaSelectionIdentity('CONVERGENCE_QUANTITY',level);await page.locator(`[data-lfea-table-record="${levelId}"]`).click();expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerSession())).selectedRecord.identity).toBe(levelId);await expect(page.locator('.lfea-record-details')).toContainText(level.levelId); });

test('T3 raw stress remains discrete and Local FEA survives Workspace replacement and clear', async ({page}) => { await page.goto('/');await openLocalFea(page);await importSource(page,'t3-review.json',t3.review);await expect(page.locator('.lfea-svg__stress-fill')).toHaveCount(t3.review.geometryReview.elements.length);const before=(await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel())).semanticHash;await page.evaluate((rawPackage)=>EventBus.publish('dataset:loadRequested',{rawPackage,sourceName:'workspace.json'}),WORKSPACE_FIXTURE);await expect.poll(()=>page.evaluate(()=>AnalysisWorkspace.getSnapshot().status)).toBe('ready');expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel())).semanticHash).toBe(before);expect((await page.evaluate(()=>AnalysisWorkspace.getApplicationViewState())).activeViewId).toBe('WORKSPACE');await page.getByRole('button',{name:'Clear',exact:true}).click();expect((await page.evaluate(()=>AnalysisWorkspace.getSnapshot())).status).toBe('empty');expect((await page.evaluate(()=>AnalysisWorkspace.getLfeaConsumerViewModel())).semanticHash).toBe(before); });

test('teardown removes Local FEA DOM listeners and active object URLs', async ({page}) => { await page.addInitScript(()=>{globalThis.__lfeaTeardown={created:0,revoked:0};const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=(blob)=>{globalThis.__lfeaTeardown.created+=1;return create(blob);};URL.revokeObjectURL=(url)=>{globalThis.__lfeaTeardown.revoked+=1;return revoke(url);};});await page.goto('/');await openLocalFea(page);await importSource(page,'export.json',q4.exportValue);await page.getByRole('button',{name:'Supplied Files',exact:true}).click();const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download review.json',exact:true}).click()]);await download.path();await expect.poll(()=>page.evaluate(()=>globalThis.__lfeaTeardown.revoked)).toBe(1);await page.evaluate(()=>AnalysisWorkspace.destroy());await expect(page.locator('#root')).toBeEmpty();expect(await page.evaluate(()=>globalThis.__lfeaTeardown.created)).toBe(await page.evaluate(()=>globalThis.__lfeaTeardown.revoked)); });
