import { deepFreeze, semanticHash } from '../shared-piping-model/index.js';
import { INITIAL_LFEA_CONSUMER_PROFILE, LFEA_CONSUMER_PROFILE_SCHEMA } from './constants.js';
const PROFILE_INPUT_KEYS=Object.freeze(['schema','profileIdentity','maximumSourceBytes','maximumNodes','maximumElements','maximumRawStressRows','maximumProjectedStressRows','maximumConvergenceRows','maximumSuppliedExportFiles','tablePageSize']);
const PROFILE_KEYS=Object.freeze([...PROFILE_INPUT_KEYS,'semanticHash']);
export function createLfeaConsumerProfile(value){assertRecord(value,'LFEA consumer profile');exactKeys(value,PROFILE_INPUT_KEYS,'LFEA consumer profile');if(value.schema!==LFEA_CONSUMER_PROFILE_SCHEMA)throw new TypeError('Invalid lfea-consumer-profile/v1 schema.');const base={schema:LFEA_CONSUMER_PROFILE_SCHEMA,profileIdentity:nonempty(value.profileIdentity,'profileIdentity'),maximumSourceBytes:positiveInteger(value.maximumSourceBytes,'maximumSourceBytes'),maximumNodes:positiveInteger(value.maximumNodes,'maximumNodes'),maximumElements:positiveInteger(value.maximumElements,'maximumElements'),maximumRawStressRows:positiveInteger(value.maximumRawStressRows,'maximumRawStressRows'),maximumProjectedStressRows:positiveInteger(value.maximumProjectedStressRows,'maximumProjectedStressRows'),maximumConvergenceRows:positiveInteger(value.maximumConvergenceRows,'maximumConvergenceRows'),maximumSuppliedExportFiles:positiveInteger(value.maximumSuppliedExportFiles,'maximumSuppliedExportFiles'),tablePageSize:positiveInteger(value.tablePageSize,'tablePageSize')};return deepFreeze({...base,semanticHash:semanticHash(base)});}
export function createInitialLfeaConsumerProfile(){return createLfeaConsumerProfile({...INITIAL_LFEA_CONSUMER_PROFILE});}
export function validateLfeaConsumerProfile(value){const errors=[];try{assertRecord(value,'LFEA consumer profile');exactKeys(value,PROFILE_KEYS,'LFEA consumer profile');const{semanticHash:declared,...base}=value;const expected=createLfeaConsumerProfile(base);if(declared!==expected.semanticHash)errors.push('LFEA consumer profile semantic hash mismatch.');}catch(error){errors.push(error.message);}return deepFreeze({ok:errors.length===0,errors});}
function assertRecord(value,name){if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError(`${name} must be a record.`);}
function exactKeys(value,keys,name){const actual=Object.keys(value).sort(),expected=[...keys].sort();if(JSON.stringify(actual)!==JSON.stringify(expected))throw new TypeError(`${name} keys are not closed.`);}
function nonempty(value,name){if(typeof value!=='string'||!value.trim())throw new TypeError(`${name} must be non-empty text.`);return value;}
function positiveInteger(value,name){if(!Number.isInteger(value)||value<=0)throw new TypeError(`${name} must be a positive integer.`);return value;}
