import { deepFreeze, semanticHash } from '../shared-piping-model/index.js';
import { LFEA_CONSUMER_SESSION_SCHEMA,LFEA_CONSUMER_STATUSES,LFEA_LAYER_IDS,LFEA_RESULT_MODES,LFEA_SECTION_IDS,LFEA_SELECTION_TYPES,LFEA_SOURCE_KINDS,LFEA_STRESS_COMPONENTS } from './constants.js';
import { normalizeTablePages } from './pagination.js';
export const LFEA_TABLE_IDS=Object.freeze(['nodes','elements','loads','constraints','displacements','reactions','rawStress','qualification','diagnostics','projectedStress','convergence','suppliedFiles']);
const SESSION_KEYS=Object.freeze(['schema','status','sourceName','sourceKind','sourceByteLength','reviewIdentity','reviewSemanticHash','exportIdentity','exportSemanticHash','activeSection','resultMode','stressComponent','layerVisibility','selectedRecord','tablePages','diagnostics','version','semanticHash']);
export function createEmptyLfeaConsumerSession(current=null){return finalize({schema:LFEA_CONSUMER_SESSION_SCHEMA,status:LFEA_CONSUMER_STATUSES.EMPTY,sourceName:null,sourceKind:null,sourceByteLength:0,reviewIdentity:null,reviewSemanticHash:null,exportIdentity:null,exportSemanticHash:null,activeSection:LFEA_SECTION_IDS[0],resultMode:LFEA_RESULT_MODES.RAW,stressComponent:'VON_MISES',layerVisibility:initialLayers(),selectedRecord:null,tablePages:normalizeTablePages({},LFEA_TABLE_IDS),diagnostics:[],version:current?(current.version||0)+1:0});}
export function createQualifiedLfeaConsumerSession(bundle,current=null){if(!bundle?.review)throw new TypeError('Qualified Local FEA source bundle is required.');return finalize({schema:LFEA_CONSUMER_SESSION_SCHEMA,status:LFEA_CONSUMER_STATUSES.QUALIFIED,sourceName:text(bundle.sourceName,'sourceName'),sourceKind:bundle.sourceKind,sourceByteLength:nonnegativeInteger(bundle.sourceByteLength,'sourceByteLength'),reviewIdentity:text(bundle.review.reviewIdentity,'reviewIdentity'),reviewSemanticHash:text(bundle.review.semanticHash,'reviewSemanticHash'),exportIdentity:bundle.export?.exportIdentity||null,exportSemanticHash:bundle.export?.semanticHash||null,activeSection:LFEA_SECTION_IDS[0],resultMode:LFEA_RESULT_MODES.RAW,stressComponent:'VON_MISES',layerVisibility:initialLayers(),selectedRecord:null,tablePages:normalizeTablePages({},LFEA_TABLE_IDS),diagnostics:[],version:(current?.version||0)+1});}
export function createFailedLfeaConsumerSession(current,diagnostic,capacityBlocked=false){const base=current||createEmptyLfeaConsumerSession();return finalize({...withoutHash(base),status:capacityBlocked?LFEA_CONSUMER_STATUSES.CAPACITY_BLOCKED:LFEA_CONSUMER_STATUSES.REJECTED,diagnostics:[normalizeDiagnostic(diagnostic)],version:base.version+1});}
export function updateLfeaConsumerSession(current,changes){const base=withoutHash(current),next={...base,...changes,tablePages:changes.tablePages?normalizeTablePages(changes.tablePages,LFEA_TABLE_IDS):base.tablePages,version:base.version+1};validateSessionBase(next);return finalize(next);}
export function validateLfeaConsumerSession(value){const errors=[];try{assertRecord(value,'LFEA consumer session');exactKeys(value,SESSION_KEYS,'LFEA consumer session');validateSessionBase(withoutHash(value));if(value.semanticHash!==semanticHash(sessionHashPayload(withoutHash(value))))errors.push('LFEA consumer session semantic hash mismatch.');}catch(error){errors.push(error.message);}return deepFreeze({ok:errors.length===0,errors});}
function finalize(base){validateSessionBase(base);return deepFreeze({...base,semanticHash:semanticHash(sessionHashPayload(base))});}
function validateSessionBase(value){if(value.schema!==LFEA_CONSUMER_SESSION_SCHEMA)throw new TypeError('Invalid lfea-consumer-session/v1 schema.');if(!Object.values(LFEA_CONSUMER_STATUSES).includes(value.status))throw new TypeError('LFEA consumer session status is invalid.');if(value.sourceName!==null)text(value.sourceName,'sourceName');if(value.sourceKind!==null&&!Object.values(LFEA_SOURCE_KINDS).includes(value.sourceKind))throw new TypeError('LFEA source kind is invalid.');nonnegativeInteger(value.sourceByteLength,'sourceByteLength');for(const key of ['reviewIdentity','reviewSemanticHash','exportIdentity','exportSemanticHash'])if(value[key]!==null)text(value[key],key);if(!LFEA_SECTION_IDS.includes(value.activeSection))throw new TypeError('LFEA active section is invalid.');if(!Object.values(LFEA_RESULT_MODES).includes(value.resultMode))throw new TypeError('LFEA result mode is invalid.');if(!LFEA_STRESS_COMPONENTS.includes(value.stressComponent))throw new TypeError('LFEA stress component is invalid.');validateLayerVisibility(value.layerVisibility);validateSelection(value.selectedRecord);validateTablePages(value.tablePages);if(!Array.isArray(value.diagnostics))throw new TypeError('LFEA diagnostics must be an array.');value.diagnostics.forEach(validateDiagnostic);nonnegativeInteger(value.version,'version');if(value.status===LFEA_CONSUMER_STATUSES.EMPTY)validateEmpty(value);if(value.status===LFEA_CONSUMER_STATUSES.QUALIFIED)validateQualified(value);}
function validateEmpty(value){if(value.sourceName!==null||value.sourceKind!==null||value.sourceByteLength!==0||value.reviewIdentity!==null||value.reviewSemanticHash!==null||value.exportIdentity!==null||value.exportSemanticHash!==null)throw new TypeError('Empty LFEA session exposes source identity.');if(value.diagnostics.length)throw new TypeError('Empty LFEA session must not contain diagnostics.');}
function validateQualified(value){text(value.sourceName,'sourceName');if(!Object.values(LFEA_SOURCE_KINDS).includes(value.sourceKind))throw new TypeError('Qualified LFEA session requires source kind.');text(value.reviewIdentity,'reviewIdentity');text(value.reviewSemanticHash,'reviewSemanticHash');if(value.sourceKind===LFEA_SOURCE_KINDS.EVIDENCE_EXPORT){text(value.exportIdentity,'exportIdentity');text(value.exportSemanticHash,'exportSemanticHash');}if(value.diagnostics.length)throw new TypeError('Qualified LFEA session must not contain diagnostics.');}
function validateLayerVisibility(value){assertRecord(value,'LFEA layer visibility');exactKeys(value,LFEA_LAYER_IDS,'LFEA layer visibility');if(Object.values(value).some((visible)=>typeof visible!=='boolean'))throw new TypeError('LFEA layer visibility must be boolean.');}
function validateSelection(value){if(value===null)return;assertRecord(value,'LFEA selected record');const keys=Object.keys(value);if(!keys.includes('type')||!keys.includes('identity')||keys.some((key)=>!['type','identity','tableId'].includes(key)))throw new TypeError('LFEA selected record keys are invalid.');if(!LFEA_SELECTION_TYPES.includes(value.type))throw new TypeError('LFEA selected-record type is invalid.');text(value.identity,'selectedRecord.identity');if(value.tableId!==undefined&&!LFEA_TABLE_IDS.includes(value.tableId))throw new TypeError('LFEA selected-record table is invalid.');}
function validateTablePages(value){assertRecord(value,'LFEA table pages');exactKeys(value,LFEA_TABLE_IDS,'LFEA table pages');for(const page of Object.values(value))if(!Number.isInteger(page)||page<1)throw new TypeError('LFEA table page must be a positive integer.');}
function validateDiagnostic(value){assertRecord(value,'LFEA diagnostic');if(!['ERROR','WARNING','INFORMATION'].includes(value.severity))throw new TypeError('LFEA diagnostic severity is invalid.');text(value.code,'diagnostic.code');text(value.message,'diagnostic.message');}
function sessionHashPayload(base){return{...base,sourceName:null,diagnostics:base.diagnostics.map((row)=>({...row,sourceName:null}))};}
function initialLayers(){return deepFreeze(Object.fromEntries(LFEA_LAYER_IDS.map((id)=>[id,id!=='PROJECTED_STRESS'])));}
function normalizeDiagnostic(value){return deepFreeze({severity:value?.severity||'ERROR',code:String(value?.code||'LFEA_SOURCE_REJECTED'),message:String(value?.message||'LFEA source was rejected.'),sourceName:value?.sourceName||null,sourceKind:value?.sourceKind||null,capacityField:value?.capacityField||null,requested:value?.requested??null,limit:value?.limit??null,previousQualifiedReviewRetained:Boolean(value?.previousQualifiedReviewRetained)});}
function withoutHash(value){const{semanticHash:_hash,...base}=value||{};return base;}
function assertRecord(value,name){if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError(`${name} must be a record.`);}
function exactKeys(value,expected,name){const actual=Object.keys(value).sort(),keys=[...expected].sort();if(JSON.stringify(actual)!==JSON.stringify(keys))throw new TypeError(`${name} keys are not closed.`);}
function text(value,name){if(typeof value!=='string'||!value.trim())throw new TypeError(`${name} must be non-empty text.`);return value;}
function nonnegativeInteger(value,name){if(!Number.isInteger(value)||value<0)throw new TypeError(`${name} must be a nonnegative integer.`);return value;}
