export const SOURCE_SCHEMA = 'local-trunnion-footprint-source/v1';
export const MODEL_SCHEMA = 'local-trunnion-footprint-model/v1';
export const RESULT_SCHEMA = 'local-trunnion-footprint-result/v1';
export const QUALIFICATION_PROFILE_SCHEMA = 'local-trunnion-footprint-qualification-profile/v1';
export const ENGINEERING_LEVEL = 'TRUNNION_FOOTPRINT_PIPE_SHELL_LOAD_INTRODUCTION_ONLY';
export const WORKFLOW_VERSION = 'LAFEA.5';

export const QUALIFICATION_STATES = Object.freeze({
  ACCEPTED: 'ACCEPTED',
  REJECTED_SOURCE_EVIDENCE: 'REJECTED_SOURCE_EVIDENCE',
  REJECTED_GEOMETRY: 'REJECTED_GEOMETRY',
  REJECTED_FOOTPRINT: 'REJECTED_FOOTPRINT',
  REJECTED_LOAD_DISTRIBUTION: 'REJECTED_LOAD_DISTRIBUTION',
  REJECTED_SHELL_MODEL: 'REJECTED_SHELL_MODEL',
  REJECTED_SHELL_RESULT: 'REJECTED_SHELL_RESULT',
  UNSUPPORTED_REQUEST: 'UNSUPPORTED_REQUEST',
  NUMERICAL_FAILURE: 'NUMERICAL_FAILURE',
});

export const ASSESSMENT_CLASSIFICATIONS = Object.freeze([
  'FOOTPRINT_ADJACENT',
  'NEAR_FIELD',
  'FAR_FIELD',
  'BOUNDARY_INFLUENCED',
]);

export const FORMULA_IDS = Object.freeze({
  REFERENCE_TRANSFER: 'ATTACHMENT_REFERENCE_TRANSFER_V1',
  TRIBUTARY_WEIGHT: 'FOOTPRINT_TRIBUTARY_LINE_WEIGHT_V1',
  WEIGHTED_FIT: 'WEIGHTED_FORCE_ONLY_RESULTANT_FIT_V1',
  RECONSTRUCTION: 'RESULTANT_RECONSTRUCTION_V1',
});

export const MANDATORY_LIMITATIONS = Object.freeze([
  'NO_TRUNNION_STIFFNESS',
  'NO_WELD_STRESS',
  'NO_CONTACT',
  'NO_PRESSURE_SUPERPOSITION',
  'NO_CODE_COMPLIANCE',
  'RAW_SHELL_STRESS_ONLY',
  'FOOTPRINT_ADJACENT_PEAKS_ARE_LOAD_INTRODUCTION_SENSITIVE',
]);

export const CANONICAL_UNITS = Object.freeze({
  length: 'mm', force: 'N', moment: 'N·mm', stress: 'MPa', rotation: 'rad',
});

export const RESULT_REQUESTS = Object.freeze({
  retainGeneratedShellModel: true,
  retainRawShellResult: true,
  governingMetric: 'COMBINED_VON_MISES',
});