import { deepFreeze } from '../shared-piping-model/index.js';

export const PRE_FEА_CHECK_REQUEST_SCHEMA = 'pre-fea-piping-check-request/v1';
export const COMMON_ENRICHED_INPUT_SCHEMA = 'common-enriched-piping-input/v1';
export const PRE_FEA_CHECK_REPORT_SCHEMA = 'pre-fea-piping-check-report/v1';
export const GOVERNED_TOPOLOGY_POS_SCHEMA = 'governed-topology-pos/v1';
export const FIELD_RESOLUTION_SCHEMA = 'field-resolution-record/v1';
export const METHOD_REQUIREMENT_REGISTRY_SCHEMA = 'non-fea-method-requirement-registry/v1';
export const LOAD_CASE_BASIS_SCHEMA = 'governed-piping-load-case-basis/v1';
export const QUALIFICATION_PROFILE_SCHEMA = 'pre-fea-piping-qualification-profile/v1';
export const LINEAGE_GRAPH_SCHEMA = 'common-piping-lineage-graph/v1';
export const ENRICHED_STAGED_JSON_SCHEMA = 'enriched-staged-piping-json/v1';

export const AUTHORITY_LEVEL = deepFreeze({
  SOURCE_EXPLICIT: 'SOURCE_EXPLICIT',
  SOURCE_INHERITED: 'SOURCE_INHERITED',
  EXACT_APPROVED_MASTER: 'EXACT_APPROVED_MASTER',
  ACCEPTED_OVERRIDE: 'ACCEPTED_OVERRIDE',
  CONFIGURED_DERIVATION: 'CONFIGURED_DERIVATION',
  PROJECT_CONFIGURED_DEFAULT: 'PROJECT_CONFIGURED_DEFAULT',
  BLOCK: 'BLOCK',
});

export const AUTHORITY_HIERARCHY = deepFreeze([
  AUTHORITY_LEVEL.SOURCE_EXPLICIT,
  AUTHORITY_LEVEL.SOURCE_INHERITED,
  AUTHORITY_LEVEL.EXACT_APPROVED_MASTER,
  AUTHORITY_LEVEL.ACCEPTED_OVERRIDE,
  AUTHORITY_LEVEL.CONFIGURED_DERIVATION,
  AUTHORITY_LEVEL.PROJECT_CONFIGURED_DEFAULT,
  AUTHORITY_LEVEL.BLOCK,
]);

export const FIELD_RESOLUTION_STATUS = deepFreeze({
  RESOLVED_SOURCE: 'RESOLVED_SOURCE',
  RESOLVED_INHERITED: 'RESOLVED_INHERITED',
  RESOLVED_EXACT_MASTER: 'RESOLVED_EXACT_MASTER',
  RESOLVED_OVERRIDE: 'RESOLVED_OVERRIDE',
  RESOLVED_CONFIGURED_DERIVATION: 'RESOLVED_CONFIGURED_DERIVATION',
  RESOLVED_CONFIGURED_DEFAULT: 'RESOLVED_CONFIGURED_DEFAULT',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  BLOCKED_MISSING: 'BLOCKED_MISSING',
  BLOCKED_AMBIGUOUS: 'BLOCKED_AMBIGUOUS',
  BLOCKED_CONFLICT: 'BLOCKED_CONFLICT',
  BLOCKED_STALE_SOURCE: 'BLOCKED_STALE_SOURCE',
  BLOCKED_UNAPPROVED: 'BLOCKED_UNAPPROVED',
  BLOCKED_OUTSIDE_SCOPE: 'BLOCKED_OUTSIDE_SCOPE',
});

export const RESOLVED_FIELD_STATUSES = deepFreeze([
  FIELD_RESOLUTION_STATUS.RESOLVED_SOURCE,
  FIELD_RESOLUTION_STATUS.RESOLVED_INHERITED,
  FIELD_RESOLUTION_STATUS.RESOLVED_EXACT_MASTER,
  FIELD_RESOLUTION_STATUS.RESOLVED_OVERRIDE,
  FIELD_RESOLUTION_STATUS.RESOLVED_CONFIGURED_DERIVATION,
  FIELD_RESOLUTION_STATUS.RESOLVED_CONFIGURED_DEFAULT,
]);

export const BLOCKED_FIELD_STATUSES = deepFreeze([
  FIELD_RESOLUTION_STATUS.BLOCKED_MISSING,
  FIELD_RESOLUTION_STATUS.BLOCKED_AMBIGUOUS,
  FIELD_RESOLUTION_STATUS.BLOCKED_CONFLICT,
  FIELD_RESOLUTION_STATUS.BLOCKED_STALE_SOURCE,
  FIELD_RESOLUTION_STATUS.BLOCKED_UNAPPROVED,
  FIELD_RESOLUTION_STATUS.BLOCKED_OUTSIDE_SCOPE,
]);

export const TARGET_KIND = deepFreeze({
  PROJECT: 'PROJECT',
  LINE: 'LINE',
  BRANCH: 'BRANCH',
  POS: 'POS',
  COMPONENT: 'COMPONENT',
  SUPPORT: 'SUPPORT',
});

export const NON_FEA_METHOD = deepFreeze({
  WEIGHT_AND_GRAVITY: 'WEIGHT_AND_GRAVITY',
  SUSTAINED_REACTIONS: 'SUSTAINED_REACTIONS',
  SUSTAINED_MEMBER_ACTIONS: 'SUSTAINED_MEMBER_ACTIONS',
  SUSTAINED_STRESS: 'SUSTAINED_STRESS',
  THERMAL_FREE_DISPLACEMENT: 'THERMAL_FREE_DISPLACEMENT',
  RESTRAINT_REACTIONS: 'RESTRAINT_REACTIONS',
  VERTICAL_CONTACT: 'VERTICAL_CONTACT',
  COMBINED_OPERATING_REACTION: 'COMBINED_OPERATING_REACTION',
  ENRICHED_STAGED_JSON_EXPORT: 'ENRICHED_STAGED_JSON_EXPORT',
});

export const METHOD_READINESS_STATE = deepFreeze({
  READY: 'READY',
  BLOCKED_MISSING_FIELDS: 'BLOCKED_MISSING_FIELDS',
  BLOCKED_AMBIGUOUS_FIELDS: 'BLOCKED_AMBIGUOUS_FIELDS',
  BLOCKED_CONFLICTING_FIELDS: 'BLOCKED_CONFLICTING_FIELDS',
  BLOCKED_STALE_SOURCE: 'BLOCKED_STALE_SOURCE',
  BLOCKED_UNAPPROVED_FIELDS: 'BLOCKED_UNAPPROVED_FIELDS',
  BLOCKED_APPLICABILITY: 'BLOCKED_APPLICABILITY',
  NOT_QUALIFIED: 'NOT_QUALIFIED',
  NOT_REQUESTED: 'NOT_REQUESTED',
});

export const SEAL_DECISION = deepFreeze({
  READY: 'READY',
  PARTIALLY_READY: 'PARTIALLY_READY',
  BLOCKED: 'BLOCKED',
});

export const PREFLIGHT_GATE = deepFreeze({
  SOURCE_MODEL: 'A_SOURCE_MODEL',
  TOPOLOGY_POS: 'B_TOPOLOGY_POS',
  PROJECT_DATA: 'C_PROJECT_DATA',
  ENGINEERING_MASTERS: 'D_ENGINEERING_MASTERS',
  ENRICHMENT: 'E_ENRICHMENT',
  DEFAULT_PREVIEW: 'F_DEFAULT_PREVIEW',
  ENGINEERING_APPLICABILITY: 'G_ENGINEERING_APPLICABILITY',
  SEAL_DECISION: 'H_SEAL_DECISION',
});

export const PREFLIGHT_GATE_ORDER = deepFreeze(Object.values(PREFLIGHT_GATE));

export const GATE_STATE = deepFreeze({
  PASSED: 'PASSED',
  BLOCKED: 'BLOCKED',
});

export const LOAD_CASE = deepFreeze({
  EMPTY: 'EMPTY',
  W: 'W',
  P: 'P',
  W_PLUS_P: 'W+P',
  OPE: 'OPE',
  HYD: 'HYD',
  THERMAL_ONLY: 'THERMAL_ONLY',
});

export const CANONICAL_UNITS = deepFreeze({
  LENGTH: 'm',
  AREA: 'm2',
  SECOND_MOMENT: 'm4',
  SECTION_MODULUS: 'm3',
  MASS: 'kg',
  MASS_PER_LENGTH: 'kg/m',
  DENSITY: 'kg/m3',
  FORCE: 'N',
  MOMENT: 'N*m',
  PRESSURE: 'Pa',
  ELASTIC_MODULUS: 'Pa',
  TRANSLATIONAL_STIFFNESS: 'N/m',
  ROTATIONAL_STIFFNESS: 'N*m/rad',
  TEMPERATURE: 'K',
  ACCELERATION: 'm/s2',
  DIMENSIONLESS: '1',
  DESIGNATION: 'designation',
  BOOLEAN: 'boolean',
  VECTOR: 'unit-vector',
});

export const PACKAGE_BLOCKING_GATES = deepFreeze([
  PREFLIGHT_GATE.SOURCE_MODEL,
  PREFLIGHT_GATE.TOPOLOGY_POS,
]);

export const SCHEDULE_FIELD = 'schedule';
